// generated by PromptPal cli. PLEASE DO NOT EDIT
package example
type PPPrompts string

const (
	
	PPPromptEcho PPPrompts = "XMkwB53W58vz"
	
	PPPromptTest1 PPPrompts = "dgJe7a8WGVZj"
	
)


type PPPromptEchoVariables struct {
	
	Text string `json:"text"`
	
}

type PPPromptTest1Variables struct {
	
}



